name: macos-build
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, macos-15-intel]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Setup Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            zig/.zig-cache
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-
      - name: Setup LLVM
        run: |
          brew install llvm gcc@15 zig sdl2 cmake protobuf
          cp /opt/homebrew/opt/llvm/bin/llvm-objcopy /opt/homebrew/opt/llvm/bin/objcopy || cp /usr/local/opt/llvm/bin/llvm-objcopy /usr/local/opt/llvm/bin/objcopy
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - uses: denoland/setup-deno@v2
      - name: Build Web UI
        run: |
          cd webui/rockbox
          deno install
          deno run build
      - name: Build Rockbox Lib
        run: |
          export PATH="/opt/homebrew/opt/llvm/bin:/usr/local/opt/llvm/bin:$PATH"
          mkdir -p build-lib
          cd build-lib
          ../tools/configure --target=sdlapp --type=N --lcdwidth=320 --lcdheight=240 --prefix=/usr/local && cp ../autoconf/autoconf.h .
          make lib -j8
      - name: Skip Rust Warnings
        run: echo "RUSTFLAGS=-A warnings" >> $GITHUB_ENV
      - name: Build Rust Libs
        run: |
          cargo build -p rockbox-cli --release
          cargo build -p rockbox-server --release
          cargo build -p rockbox --release
      - name: Build Rockbox Binary
        run: zig build
        working-directory: zig
      - name: Install
        run: sudo make install
        working-directory: build-lib
      - name: Show artifacts
        run: |
          echo build-lib
          ls -l build-lib
          echo zig-out
          ls -l zig/zig-out/bin
          echo target
          ls -l target/release
          echo lib
          ls -l /usr/local/lib/rockbox/*
          echo share
          ls -l /usr/local/share/rockbox
      - name: Show Rockbox version
        run: |
          ./target/release/rockbox --version
          ./zig/zig-out/bin/rockboxd --version
